# Generated by Django 4.1.4 on 2022-12-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('ContactNo', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Programming_Language', models.CharField(max_length=100)),
                ('Education', models.CharField(max_length=100)),
                ('Prefered_loc', models.CharField(max_length=100)),
                ('Prof_image', models.ImageField(upload_to='')),
                ('Project', models.TextField()),
            ],
        ),
    ]
